### PR TITLE
Feature/support more tags

### PR DESCRIPTION
**Pull request by dornah**

### CODE REVIEW

**Comment by chrisyue** [comment]
thanks for the PR @dornah 
but why close it? it looks good to me, just some small fixes to fit the coding standard.

**Comment by dornah** [comment]
Hi @chrisyue,
Thanks for reopening my PR and the great library.
I will update the PR with fixes soon.

**Comment by chrisyue** [comment]
@dornah it's easy to fix the coding standard. just run `vendor/bin/php-cs-fixer fix` and all should be done.

**Comment by dornah** [comment]
Thanks. I ran the command and squashed the commits.

**Comment by chrisyue** [comment]
@dornah I've already working on it #31

**Comment by dornah** [comment]
Cool, thanks :-)

**Pull request closed without merging**
