### PR TITLE
Byterange support added

### PR DESCRIPTION
**Pull request by brucebertrand**
Hi.
I added EXT-X-BYTERANGE support.
It works with my use case, but I haven't checked it exhaustively against everything else in the library.

### CODE REVIEW

**Comment by chrisyue** [comment]
looks great! 

but i'd like getByteRange() return an array containing `length` and `offset`

**Comment by brucebertrand** [comment]
That makes sense.

Named keys?  `getByteRange()['length']` and `getByteRange()['offset']` ?

Since, like in my case, there might be thousands of MediaSegments for each Playlist, how about an SplFixedArray(2).  You loose the named keys, but it's much faster.  Also, you don't have to worry about 
OutOfBoundsException being thrown if if you try to access `getByteRange()[1]`.

Perhaps the protected member is an SplFixedArray(2), and there's a separate getter that returns each version?  Something like:
`protected $byterange = new SplFixedArray();`
`...`
`function getByteRange() { return ['length' => $arr[0], 'offset' => $arr[1]]; }`
`function getByteRangeFixed() { return $byterange; }`

**Comment by brucebertrand** [comment]
I should have clarified my rationale.
If you use EXT-X-BYTERANGE, length is mandatory, but offset is optional.

If the protected member is a normal array, access to offset requires either a call to `isset('offset', $thearray)`, or handling an OutOfBoundsException.

For an `SplFixedArray(2)` you can always access `$thearray[1]` without worrying about an exception. You still have to check it for null.

Perhaps my use case is unusual in benefiting from this kind of optimization.  On every request I'm parsing and manipulating thousands of MediaSegments.

**Comment by chrisyue** [comment]
I am OK with `SplFixedArray`, and I think one `getByteRange` function directly returning a `SplFixedArray` is enough ;-)

**Comment by brucebertrand** [comment]
Done, I think.

**Comment by chrisyue** [comment]
@brucebertrand thanks for the code.

However the travis-ci failed the test, because there are some pieces of code which syntax is not supported by PHP 5.3.

As we've already have same thoughts on how to code, and there is not much code to write,  I'd like to make a new PR to fix those minor issues, and write some tests.

**Comment by chrisyue** [comment]
#11 is merged

**Pull request closed without merging**
